# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0002_avaliation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
